#!/usr/bin/env node
/**
 * Import gruppi 6–10 in data/bandi.json (49 record; salta voce 76 = Nuova Sabatini già in mimit001sabatini).
 * Esegui: node scripts/merge_bandi_g6to10.js
 */
const fs = require('fs');
const path = require('path');
const JSON_PATH = path.join(__dirname, '..', 'data', 'bandi.json');

const NUOVI = [
  { id: 'imp26g06piesrd04b', titolo: 'Piemonte CSR — SRD04.B tutela elementi naturaliformi agroecosistema', ente: 'Regione Piemonte', tipo_ente: 'regione', regione: 'Piemonte', url_bando: 'https://www.regione.piemonte.it/web/agricoltura', url_domanda: 'https://www.regione.piemonte.it/web/agricoltura', data_scadenza: '2026-05-29', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese_agricole'], settori: ['agricoltura'], finalita: ['agroecosistema'], keywords: ['piemonte', 'srd04', 'b'], descrizione: 'Hub agricoltura; avviso SRD04.B su BUR/agea.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06piepred', titolo: 'Piemonte — Danni da predazione grandi carnivori (bando 2/2025)', ente: 'Regione Piemonte', tipo_ente: 'regione', regione: 'Piemonte', url_bando: 'https://www.regione.piemonte.it/web/agricoltura', url_domanda: 'https://www.regione.piemonte.it/web/agricoltura', data_scadenza: '2026-04-24', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['allevatori'], settori: ['allevamento'], finalita: ['predazione'], keywords: ['piemonte', 'carnivori', 'allevatori'], descrizione: 'Contributi per danni da predazione; verificare avviso annualità.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06csenzasic', titolo: 'CCIAA Cosenza — Sicurezza luoghi di lavoro (IV edizione)', ente: 'Camera di Commercio Cosenza', tipo_ente: 'cciaa', regione: 'Calabria', provincia: 'CS', url_bando: 'https://www.cs.camcom.it', url_domanda: 'https://www.cs.camcom.it', data_scadenza: '2026-09-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['tutti'], finalita: ['sicurezza'], keywords: ['cosenza', 'sicurezza'], descrizione: 'Sezione bandi Camera Cosenza per investimenti in sicurezza.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06conbamb', titolo: 'Con i Bambini — Progetto prevenzione dipendenze (bandi terzo settore)', ente: 'Con i Bambini Impresa Sociale', tipo_ente: 'altro', regione: 'Nazionale', url_bando: 'https://www.conibambini.it', url_domanda: 'https://www.conibambini.it', data_scadenza: '2026-05-21', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['terzo_settore'], settori: ['sociale'], finalita: ['prevenzione'], keywords: ['con i bambini', 'dipendenze'], descrizione: 'Ente non PA; verificare ammissibilità link in policy sito.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06sicilia10', titolo: 'Sicilia CSR — SRG10 promozione prodotti di qualità', ente: 'Regione Siciliana', tipo_ente: 'regione', regione: 'Sicilia', url_bando: 'https://www.regione.sicilia.it', url_domanda: 'https://www.regione.sicilia.it', data_scadenza: '2026-05-13', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese_agricole'], settori: ['agroalimentare'], finalita: ['qualita'], keywords: ['sicilia', 'srg10'], descrizione: 'Hub regionale; sezione agricoltura CSR SRG10.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06ersport817', titolo: 'Emilia-Romagna L.R. 8/2017 — Contributi eventi sportivi', ente: 'Regione Emilia-Romagna', tipo_ente: 'regione', regione: 'Emilia-Romagna', url_bando: 'https://www.regione.emilia-romagna.it/sport', url_domanda: 'https://www.regione.emilia-romagna.it/sport', data_scadenza: '2026-04-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['associazioni'], settori: ['sport'], finalita: ['eventi'], keywords: ['er', 'sport', 'lr 8/2017'], descrizione: 'Avvisi sport; ricercare bando annualità corrente.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06minzes', titolo: 'Ministero del Lavoro — Credito d’imposta ZES unica Mezzogiorno', ente: 'Ministero del Lavoro e delle Politiche Sociali', tipo_ente: 'ministero', regione: 'Nazionale', url_bando: 'https://www.lavoro.gov.it/temi-e-priorita/lavoro-e-imprese-meridione/zls', url_domanda: 'https://www.lavoro.gov.it/temi-e-priorita/lavoro-e-imprese-meridione/zls', data_scadenza: '2026-05-30', stato: 'aperto', tipo_contributo: 'credito_imposta', beneficiari: ['imprese'], settori: ['tutti'], finalita: ['investimenti'], keywords: ['zes', 'mezzogiorno'], descrizione: 'Credito d’imposta investimenti in ZES unica Sud; seguire decreti applicativi.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06ptpp', titolo: 'CCIAA Pistoia-Prato — Sostenibilità socio-ambientale e digit produzione', ente: 'Camera di Commercio Pistoia-Prato', tipo_ente: 'cciaa', regione: 'Toscana', provincia: 'PT', url_bando: 'https://www.pt.camcom.it', url_domanda: 'https://www.pt.camcom.it', data_scadenza: '2026-07-15', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['manifattura'], finalita: ['sostenibilita', 'digitale'], keywords: ['pistoia', 'prato'], descrizione: 'Bandi Camera PT; verificare avviso annualità.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06marecert', titolo: 'CCIAA Maremma e Tirreno — Certificazioni di qualità imprese', ente: 'Camera di Commercio Maremma e Tirreno', tipo_ente: 'cciaa', regione: 'Toscana', url_bando: 'https://www.li.camcom.it', url_domanda: 'https://www.li.camcom.it', data_scadenza: '2026-11-10', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['tutti'], finalita: ['qualita'], keywords: ['livorno', 'grosseto', 'certificazioni'], descrizione: 'Portale CCIAA Livorno-Grosseto area Maremma Tirreno.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g06marecrea', titolo: 'CCIAA Maremma e Tirreno — Creazione d’impresa', ente: 'Camera di Commercio Maremma e Tirreno', tipo_ente: 'cciaa', regione: 'Toscana', url_bando: 'https://www.li.camcom.it', url_domanda: 'https://www.li.camcom.it', data_scadenza: '2026-11-10', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['startup'], settori: ['tutti'], finalita: ['avvio_impresa'], keywords: ['maremma', 'nuova impresa'], descrizione: 'Stesso portale CCIAA; scheda creazione impresa.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07marevic', titolo: 'CCIAA Maremma e Tirreno — Imprese di vicinato Livorno-Grosseto', ente: 'Camera di Commercio Maremma e Tirreno', tipo_ente: 'cciaa', regione: 'Toscana', url_bando: 'https://www.li.camcom.it', url_domanda: 'https://www.li.camcom.it', data_scadenza: '2026-11-10', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['commercio'], finalita: ['vicinato'], keywords: ['vicinato', 'maremma'], descrizione: 'Misura imprese di vicinato; sezione bandi.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07maretur', titolo: 'CCIAA Maremma e Tirreno — Transizione sostenibile imprese turistiche', ente: 'Camera di Commercio Maremma e Tirreno', tipo_ente: 'cciaa', regione: 'Toscana', url_bando: 'https://www.li.camcom.it', url_domanda: 'https://www.li.camcom.it', data_scadenza: '2026-11-10', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['turismo'], finalita: ['sostenibilita'], keywords: ['turismo', 'maremma'], descrizione: 'Turismo sostenibile; bandi Camera.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07fisic', titolo: 'CCIAA Firenze — Sicurezza sedi aziendali città metropolitana', ente: 'Camera di Commercio Firenze', tipo_ente: 'cciaa', regione: 'Toscana', provincia: 'FI', url_bando: 'https://www.fi.camcom.it', url_domanda: 'https://www.fi.camcom.it', data_scadenza: '2026-12-31', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['tutti'], finalita: ['sicurezza'], keywords: ['firenze', 'sicurezza'], descrizione: 'Avvisi Camera Firenze per sicurezza sedi.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07fisoa', titolo: 'CCIAA Firenze — Contributi attestazione SOA', ente: 'Camera di Commercio Firenze', tipo_ente: 'cciaa', regione: 'Toscana', provincia: 'FI', url_bando: 'https://www.fi.camcom.it', url_domanda: 'https://www.fi.camcom.it', data_scadenza: '2026-05-29', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese'], settori: ['edilizia'], finalita: ['soa'], keywords: ['firenze', 'soa'], descrizione: 'Misura SOA edilizia; portale bandi FI.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07aresiena', titolo: 'CCIAA Arezzo-Siena — Competitività e sviluppo economico', ente: 'Camera di Commercio Arezzo-Siena', tipo_ente: 'cciaa', regione: 'Toscana', url_bando: 'https://www.arezzo-siena.camcom.it', url_domanda: 'https://www.arezzo-siena.camcom.it', data_scadenza: '2026-04-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['tutti'], finalita: ['competitivita'], keywords: ['arezzo', 'siena'], descrizione: 'Bandi Camera Arezzo-Siena.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07toscor17', titolo: 'Toscana L.R. 17/2025 — Valorizzazione oratori e attività oratoriali', ente: 'Regione Toscana', tipo_ente: 'regione', regione: 'Toscana', url_bando: 'https://www.regione.toscana.it', url_domanda: 'https://www.regione.toscana.it', data_scadenza: '2026-05-04', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_no_profit'], settori: ['sociale'], finalita: ['cultura'], keywords: ['toscana', 'oratori'], descrizione: 'Avviso su portale Regione Toscana bandi.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07toscfsefam', titolo: 'FSE+ Toscana — Servizi a famiglie e minori (servizi sociali)', ente: 'Regione Toscana', tipo_ente: 'regione', regione: 'Toscana', url_bando: 'https://www.regione.toscana.it', url_domanda: 'https://www.regione.toscana.it', data_scadenza: '2026-05-29', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_pubblici'], settori: ['sociale'], finalita: ['welfare'], keywords: ['fse+', 'toscana', 'minori'], descrizione: 'Priorità inclusione FSE+; cercare avviso annualità.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07toscsrh04', titolo: 'Toscana CSR — SRH04 informazione settore agricolo', ente: 'Regione Toscana', tipo_ente: 'regione', regione: 'Toscana', url_bando: 'https://www.regione.toscana.it', url_domanda: 'https://www.regione.toscana.it', data_scadenza: '2026-04-10', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese_agricole'], settori: ['agricoltura'], finalita: ['informazione'], keywords: ['toscana', 'srh04'], descrizione: 'CSR PAC; sezione agricoltura regionale.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07toscsrh05', titolo: 'Toscana CSR — SRH05 azioni dimostrative agricole', ente: 'Regione Toscana', tipo_ente: 'regione', regione: 'Toscana', url_bando: 'https://www.regione.toscana.it', url_domanda: 'https://www.regione.toscana.it', data_scadenza: '2026-04-17', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese_agricole'], settori: ['agricoltura'], finalita: ['ricerca'], keywords: ['toscana', 'srh05'], descrizione: 'Azioni dimostrative; avviso su sito regione.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g07ligsra14', titolo: 'Liguria CSR — SRA14 allevatori custodi agrobiodiversità', ente: 'Regione Liguria', tipo_ente: 'regione', regione: 'Liguria', url_bando: 'https://www.regione.liguria.it', url_domanda: 'https://www.regione.liguria.it', data_scadenza: '2026-05-15', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['allevatori'], settori: ['allevamento'], finalita: ['biodiversita'], keywords: ['liguria', 'sra14'], descrizione: 'Hub Regione Liguria agricoltura/CSR.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08siclr1', titolo: 'Sicilia L.R. 1/2024 — Iniziative territoriali sociali ed economiche', ente: 'Regione Siciliana', tipo_ente: 'regione', regione: 'Sicilia', url_bando: 'https://www.regione.sicilia.it', url_domanda: 'https://www.regione.sicilia.it', data_scadenza: '2026-04-15', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_locali'], settori: ['tutti'], finalita: ['territorio'], keywords: ['sicilia', 'lr 1/2024'], descrizione: 'Avvisi regionali; ricercare decreto annualità.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08lomteatri', titolo: 'Lombardia — Teatri di tradizione ad alto valore artistico', ente: 'Regione Lombardia', tipo_ente: 'regione', regione: 'Lombardia', url_bando: 'https://cultura.regione.lombardia.it', url_domanda: 'https://cultura.regione.lombardia.it', data_scadenza: '2026-04-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_no_profit'], settori: ['spettacolo'], finalita: ['cultura'], keywords: ['lombardia', 'teatri'], descrizione: 'Riferimento cultura regionale e MiC per spettacolo dal vivo.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08sicharry', titolo: 'Sicilia L.R. 3/2026 — Contributi imprese danni ciclone Harry', ente: 'Regione Siciliana', tipo_ente: 'regione', regione: 'Sicilia', url_bando: 'https://www.regione.sicilia.it', url_domanda: 'https://www.regione.sicilia.it', data_scadenza: '2026-04-10', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['tutti'], finalita: ['ristori'], keywords: ['sicilia', 'harry', 'ciclone'], descrizione: 'Misura straordinaria danni; avviso su GURS/bandi.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08crcmanif', titolo: 'Fondazione CRC Cuneo — Manifesta Bellezza (restauro beni culturali)', ente: 'Fondazione CRC', tipo_ente: 'altro', regione: 'Piemonte', provincia: 'CN', url_bando: 'https://www.fondazionecrc.it', url_domanda: 'https://www.fondazionecrc.it', data_scadenza: '2026-09-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_no_profit'], settori: ['cultura'], finalita: ['restauro'], keywords: ['cuneo', 'beni culturali'], descrizione: 'Fondazione bancaria; verificare policy link.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08sardalisei', titolo: 'Sardegna L.R. 20/2022 — ALISEI azioni LIS (educazione e istruzione)', ente: 'Regione Sardegna', tipo_ente: 'regione', regione: 'Sardegna', url_bando: 'https://www.regione.sardegna.it', url_domanda: 'https://www.regione.sardegna.it', data_scadenza: '2026-04-13', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['scuole'], settori: ['istruzione'], finalita: ['lis'], keywords: ['sardegna', 'alisei'], descrizione: 'Bando ALISEI; sezione istruzione regione.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08lomitin', titolo: 'Lombardia — Itinerari ed eventi turistici 2026', ente: 'Regione Lombardia', tipo_ente: 'regione', regione: 'Lombardia', url_bando: 'https://www.regione.lombardia.it', url_domanda: 'https://www.regione.lombardia.it', data_scadenza: '2026-04-22', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['turismo'], finalita: ['turismo'], keywords: ['lombardia', 'itinerari'], descrizione: 'Turismo Regione Lombardia; avviso itinerari.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08erfondstart', titolo: 'FESR Emilia-Romagna — Fondo Starter (nuova imprenditorialità a tasso agevolato)', ente: 'Regione Emilia-Romagna', tipo_ente: 'regione', regione: 'Emilia-Romagna', url_bando: 'https://fesr.regione.emilia-romagna.it/opportunita/opportunita-di-finanziamento/2026', url_domanda: 'https://fesr.regione.emilia-romagna.it/opportunita/opportunita-di-finanziamento/2026', data_scadenza: '2026-05-29', stato: 'aperto', tipo_contributo: 'tasso_agevolato', beneficiari: ['startup'], settori: ['tutti'], finalita: ['credito'], keywords: ['fondo starter', 'fesr'], descrizione: 'Opportunità 2026 FESR; selezionare scheda Fondo Starter.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08lazfresco', titolo: 'Lazio — Bando Fresco (latte fresco — storico)', ente: 'Regione Lazio', tipo_ente: 'regione', regione: 'Lazio', url_bando: 'https://www.regione.lazio.it', url_domanda: 'https://www.regione.lazio.it', data_scadenza: '2024-07-23', stato: 'chiuso', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese'], settori: ['agroalimentare'], finalita: ['latte'], keywords: ['lazio', 'fresco'], descrizione: 'Scadenza 2024 in fonti; lasciato come chiuso per tracciamento.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g08lazlr26', titolo: 'Lazio L.R. 26/2007 — Tradizioni storiche, artistiche e popolari', ente: 'Regione Lazio', tipo_ente: 'regione', regione: 'Lazio', url_bando: 'https://www.regione.lazio.it', url_domanda: 'https://www.regione.lazio.it', data_scadenza: '2026-04-16', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['associazioni'], settori: ['cultura'], finalita: ['tradizioni'], keywords: ['lazio', 'lr 26/2007'], descrizione: 'Avviso su cultura e tradizioni Lazio.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09mintourf', titolo: 'Ministero del Turismo — Filiera turistica e digitalizzazione (avvisi nazionali)', ente: 'Ministero del Turismo', tipo_ente: 'ministero', regione: 'Nazionale', url_bando: 'https://www.ministeroturismo.gov.it', url_domanda: 'https://www.ministeroturismo.gov.it', data_scadenza: null, stato: 'in_arrivo', tipo_contributo: 'misto', beneficiari: ['imprese'], settori: ['turismo'], finalita: ['digitalizzazione'], keywords: ['turismo', 'filiera'], descrizione: 'Prossime aperture; monitorare decreto e bandi Invitalia.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09lazstreet', titolo: 'Lazio L.R. 22/2020 — Street Art 2026', ente: 'Regione Lazio', tipo_ente: 'regione', regione: 'Lazio', url_bando: 'https://www.regione.lazio.it', url_domanda: 'https://www.regione.lazio.it', data_scadenza: '2026-05-15', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_locali'], settori: ['cultura'], finalita: ['urbano'], keywords: ['street art', 'lazio'], descrizione: 'Avviso street art; cultura regione Lazio.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09venocmvin', titolo: 'Veneto — OCM Vino ristrutturazione e riconversione vigneti', ente: 'Regione Veneto', tipo_ente: 'regione', regione: 'Veneto', url_bando: 'https://www.regione.veneto.it/web/agricoltura-e-foreste', url_domanda: 'https://www.regione.veneto.it/web/agricoltura-e-foreste', data_scadenza: '2026-04-14', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese_agricole'], settori: ['vitivinicolo'], finalita: ['vigneti'], keywords: ['veneto', 'ocm'], descrizione: 'Sezione vitivinicolo Veneto; campagna PNS.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09galmar', titolo: 'GAL Valli Marecchia e Conca — SRD09 servizi base popolazione rurale (enti pubblici)', ente: 'GAL Valli Marecchia e Conca', tipo_ente: 'altro', regione: 'Emilia-Romagna', url_bando: 'https://www.galappenninoriminese.it', url_domanda: 'https://www.galappenninoriminese.it', data_scadenza: '2026-07-28', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_pubblici'], settori: ['servizi'], finalita: ['rurale'], keywords: ['gal', 'marecchia', 'rimini'], descrizione: 'Verificare GAL corretto su territorio Rimini; URL da allineare a scheda ufficiale.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09erlr13', titolo: 'Emilia-Romagna L.R. 13/2021 — Editori Salone libro e Più libri più liberi', ente: 'Regione Emilia-Romagna', tipo_ente: 'regione', regione: 'Emilia-Romagna', url_bando: 'https://www.regione.emilia-romagna.it', url_domanda: 'https://www.regione.emilia-romagna.it', data_scadenza: '2026-02-27', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['editoria'], settori: ['editoria'], finalita: ['cultura'], keywords: ['editori', 'salone libro'], descrizione: 'Contributi case editrici ER; avviso cultura.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09erlr16', titolo: 'Emilia-Romagna L.R. 16/2008 — Promozione cittadinanza europea', ente: 'Regione Emilia-Romagna', tipo_ente: 'regione', regione: 'Emilia-Romagna', url_bando: 'https://www.regione.emilia-romagna.it', url_domanda: 'https://www.regione.emilia-romagna.it', data_scadenza: '2026-04-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_pubblici'], settori: ['istruzione'], finalita: ['cittadinanza'], keywords: ['cittadinanza europea'], descrizione: 'Avviso annualità su sito regione.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09erlr21', titolo: 'Emilia-Romagna L.R. 21/2012 — Studi di fattibilità fusioni Comuni', ente: 'Regione Emilia-Romagna', tipo_ente: 'regione', regione: 'Emilia-Romagna', url_bando: 'https://www.regione.emilia-romagna.it', url_domanda: 'https://www.regione.emilia-romagna.it', data_scadenza: '2026-04-13', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_locali'], settori: ['pa'], finalita: ['fusioni'], keywords: ['comuni', 'fusione'], descrizione: 'Contributi studi fusione; avviso enti locali.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09pugoliv', titolo: 'Puglia — Rigenerazione olivicola (azione 4.4 piano straordinario)', ente: 'Regione Puglia', tipo_ente: 'regione', regione: 'Puglia', url_bando: 'https://www.regione.puglia.it', url_domanda: 'https://www.regione.puglia.it', data_scadenza: '2026-04-20', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['imprese_agricole'], settori: ['olivicoltura'], finalita: ['olivo'], keywords: ['puglia', 'olivicoltura'], descrizione: 'Sezione agricoltura Puglia; avviso azione 4.4.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09lomdist', titolo: 'Lombardia — Distretti del commercio 2026', ente: 'Regione Lombardia', tipo_ente: 'regione', regione: 'Lombardia', url_bando: 'https://www.regione.lombardia.it', url_domanda: 'https://www.regione.lombardia.it', data_scadenza: '2026-07-31', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['commercio'], settori: ['commercio'], finalita: ['distretti'], keywords: ['distretti commercio'], descrizione: 'Bandi sviluppo economico Lombardia.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g09euicall4', titolo: 'European Urban Initiative — Call 4 progetti sviluppo urbano sostenibile', ente: 'Commissione europea / EUI', tipo_ente: 'altro', regione: 'Bandi Europei', url_bando: 'https://eui.eu', url_domanda: 'https://eui.eu', data_scadenza: '2026-06-15', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_pubblici'], settori: ['urbanistica'], finalita: ['sostenibilita'], keywords: ['eui', 'urban'], descrizione: 'Iniziativa urbana UE; verificare testo call su sito EUI.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10toscbirra', titolo: 'Toscana L.R. 34/2025 — Produttori birra artigianale', ente: 'Regione Toscana', tipo_ente: 'regione', regione: 'Toscana', url_bando: 'https://www.regione.toscana.it', url_domanda: 'https://www.regione.toscana.it', data_scadenza: '2026-05-26', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['birrifici'], finalita: ['promozione'], keywords: ['birra', 'toscana'], descrizione: 'Avviso LR 34/2025 su bandi regione.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10vapw5', titolo: 'CCIAA Varese — Project Work V edizione (alternanza scuola-lavoro)', ente: 'Camera di Commercio Varese', tipo_ente: 'cciaa', regione: 'Lombardia', provincia: 'VA', url_bando: 'https://www.va.camcom.it', url_domanda: 'https://www.va.camcom.it', data_scadenza: '2026-06-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['scuole'], settori: ['formazione'], finalita: ['alternanza'], keywords: ['varese', 'project work'], descrizione: 'Bandi Camera Varese formazione.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10vapw4', titolo: 'CCIAA Varese — Project Work IV edizione (storico)', ente: 'Camera di Commercio Varese', tipo_ente: 'cciaa', regione: 'Lombardia', provincia: 'VA', url_bando: 'https://www.va.camcom.it', url_domanda: 'https://www.va.camcom.it', data_scadenza: '2024-07-15', stato: 'chiuso', tipo_contributo: 'fondo_perduto', beneficiari: ['scuole'], settori: ['formazione'], finalita: ['alternanza'], keywords: ['varese', 'project work'], descrizione: 'Edizione precedente; stato chiuso.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10lomstartcup', titolo: 'Lombardia — Premio Startcup Lombardia 2026', ente: 'Regione Lombardia / Unioncamere', tipo_ente: 'regione', regione: 'Lombardia', url_bando: 'https://www.bandi.regione.lombardia.it', url_domanda: 'https://www.bandi.regione.lombardia.it', data_scadenza: null, stato: 'in_arrivo', tipo_contributo: 'fondo_perduto', beneficiari: ['startup'], settori: ['tutti'], finalita: ['competizioni'], keywords: ['startcup', 'lombardia'], descrizione: 'Prossima apertura; portale bandi Lombardia.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10lomagroind', titolo: 'Lombardia — Agroindustria startup innovative 2026', ente: 'Regione Lombardia', tipo_ente: 'regione', regione: 'Lombardia', url_bando: 'https://www.bandi.regione.lombardia.it', url_domanda: 'https://www.bandi.regione.lombardia.it', data_scadenza: null, stato: 'in_arrivo', tipo_contributo: 'fondo_perduto', beneficiari: ['startup'], settori: ['agroalimentare'], finalita: ['innovazione'], keywords: ['agroindustria', 'startup'], descrizione: 'Premio/ bando agroindustria; verificare apertura.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10lomsportass', titolo: 'Lombardia — Attività ordinaria associazioni e società sportive dilettantistiche', ente: 'Regione Lombardia', tipo_ente: 'regione', regione: 'Lombardia', url_bando: 'https://www.regione.lombardia.it', url_domanda: 'https://www.regione.lombardia.it', data_scadenza: '2026-04-23', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['associazioni'], settori: ['sport'], finalita: ['sport'], keywords: ['lombardia', 'sport'], descrizione: 'Sport e giovani regione; avviso contributi.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10lazsport9', titolo: 'Lazio L.R. 9/2010 — Sport in Comune (impianti Comuni fino 20.000 ab.)', ente: 'Regione Lazio', tipo_ente: 'regione', regione: 'Lazio', url_bando: 'https://www.regione.lazio.it', url_domanda: 'https://www.regione.lazio.it', data_scadenza: '2026-04-24', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_locali'], settori: ['sport'], finalita: ['impianti'], keywords: ['sport in comune', 'lazio'], descrizione: 'Efficientamento impianti sportivi; avviso cultura/sport Lazio.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10basnido', titolo: 'Basilicata FSE+ — Un nido per l’infanzia (servizi educativi 0-6)', ente: 'Regione Basilicata', tipo_ente: 'regione', regione: 'Basilicata', url_bando: 'https://www.regione.basilicata.it', url_domanda: 'https://www.regione.basilicata.it', data_scadenza: '2026-04-13', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_pubblici'], settori: ['infanzia'], finalita: ['educazione'], keywords: ['basilicata', 'nido', 'fse+'], descrizione: 'Avviso politiche sociali Basilicata.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10lazladit', titolo: 'Lazio — LaDIT turismo digitale ed esperienziale 2026', ente: 'Regione Lazio - Lazio Innova', tipo_ente: 'regione', regione: 'Lazio', url_bando: 'https://www.lazioinnova.it', url_domanda: 'https://www.lazioinnova.it', data_scadenza: '2026-04-25', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['PMI'], settori: ['turismo'], finalita: ['digitale'], keywords: ['ladit', 'lazio', 'turismo'], descrizione: 'Innovazione turismo Lazio; verificare bando su Lazio Innova.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true },
  { id: 'imp26g10micbib', titolo: 'MIC — Biblioteche non statali aperte al pubblico (annualità 2026)', ente: 'Ministero della Cultura', tipo_ente: 'ministero', regione: 'Nazionale', url_bando: 'https://www.cultura.gov.it/biblioteche-e-diritto-dautore', url_domanda: 'https://www.cultura.gov.it/biblioteche-e-diritto-dautore', data_scadenza: '2026-04-30', stato: 'aperto', tipo_contributo: 'fondo_perduto', beneficiari: ['enti_no_profit'], settori: ['cultura'], finalita: ['lettura'], keywords: ['biblioteche', 'mic'], descrizione: 'Avviso DG Biblioteche; seguire modulistica ministeriale.', fonte_scraping: 'import_manuale_gruppo6to10', needs_url_verification: true }
];

function normalize(b) {
  const o = {
    id: b.id,
    titolo: b.titolo,
    ente: b.ente,
    tipo_ente: b.tipo_ente,
    regione: b.regione,
    provincia: b.provincia ?? null,
    url_bando: b.url_bando,
    url_domanda: b.url_domanda,
    data_apertura: b.data_apertura ?? null,
    data_scadenza: b.data_scadenza ?? null,
    stato: b.stato,
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: b.tipo_contributo,
    beneficiari: b.beneficiari,
    settori: b.settori,
    finalita: b.finalita,
    keywords: b.keywords,
    descrizione: b.descrizione,
    data_scraping: new Date().toISOString(),
    fonte_scraping: b.fonte_scraping
  };
  if (b.needs_url_verification) o.needs_url_verification = true;
  return o;
}

const data = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
if (data.bandi.some((x) => x.id === 'imp26g06piesrd04b')) {
  console.log('Import gruppi 6–10 già presente: skip.');
  process.exit(0);
}
const idx = data.bandi.findIndex((b) => b.id === 'ei_wmumqc');
if (idx < 0) {
  console.error('ei_wmumqc non trovato');
  process.exit(1);
}
data.bandi.splice(idx, 0, ...NUOVI.map(normalize));
data.metadata.total_bandi = data.bandi.length;
data.metadata.generated_at = new Date().toISOString();
fs.writeFileSync(JSON_PATH, JSON.stringify(data, null, 2));
console.log('OK: inseriti', NUOVI.length, 'bandi. Totale:', data.bandi.length);
